from pathlib import Path
import re
path = Path('src/App.tsx')
text = path.read_text()
text = text.replace('import { ChangeEvent, DragEvent, FormEvent, useEffect, useMemo, useState } from "react";\n', 'import { ChangeEvent, DragEvent, FormEvent, useEffect, useMemo, useState } from "react";\nimport { FaCheckCircle, FaCreditCard, FaEnvelope, FaFileContract, FaGithub, FaGoogle, FaHeadset, FaInstagram, FaLinkedin, FaLock, FaMapMarkerAlt, FaPhoneAlt, FaShieldAlt, FaUserCircle } from "react-icons/fa";\n')
pattern = re.compile(r'type ContactForm = \{.*?const defaultTool: ToolId = "merge";\n', re.S)
replacement = '''type ContactForm = {\n  name: string;\n  email: string;\n  message: string;\n};\n\ntype SupportForm = {\n  name: string;\n  email: string;\n  subject: string;\n  message: string;\n};\n\ntype PreferenceSettings = {\n  marketingEmails: boolean;\n  productUpdates: boolean;\n  darkMode: boolean;\n};\n\ntype AuthMode = "login" | "signup" | "forgot" | "otpLogin" | "otpReset";\n\ntype AuthForm = {\n  name: string;\n  email: string;\n  password: string;\n  otp: string;\n  newPassword: string;\n};\n\ntype SessionUser = {\n  id: string;\n  name: string;\n  email: string;\n  phone?: string;\n  company?: string;\n  avatarUrl?: string;\n  plan: "free" | "pro" | "team";\n  preferences: PreferenceSettings;\n};\n\ntype ProfileForm = {\n  name: string;\n  email: string;\n  phone: string;\n  company: string;\n  avatarUrl: string;\n  preferences: PreferenceSettings;\n};\n\ntype AppConfig = {\n  googleLoginEnabled: boolean;\n  otpEnabled: boolean;\n  billingEnabled: boolean;\n};\n\ntype SubscriptionPlan = {\n  id: "free" | "pro" | "team";\n  title: string;\n  priceLabel: string;\n  interval: string;\n  description: string;\n  features: string[];\n  cta: string;\n};\n\ntype DashboardSummary = {\n  user: SessionUser;\n  stats: {\n    supportTickets: number;\n    contactMessages: number;\n    currentPlan: string;\n    billingStatus: string;\n  };\n};\n\nconst emptyPreferences: PreferenceSettings = {\n  marketingEmails: false,\n  productUpdates: true,\n  darkMode: false,\n};\n\nconst defaultTool: ToolId = "merge";\n'''
text = pattern.sub(replacement, text, count=1)
path.write_text(text)
